### ISSUE TITLE
Názov repozitáru

### ISSUE THREAD

**Issue by CiernaOvca** [aks-2017/semestralne-zadania-semestralne-zadanie-xhrobak-xkovacm8#1]
Dobrý deň,

chceli by sme Vás poprosiť o zmenu názvu repozitáru.
73909 - Maroš Hrobák (xhrobak)
73984 - Matúš Kováč (xkovacm8)

Ďakujeme.

**Comment by fr6nco** [comment]
dakujem za proaktivny pristup
